package com.hoolink.sdk.bo.device;

public class BroadcastGroupParamBO {

    /**
     * 关联麦克风id
     * 表字段 : broadcast_group.device_id
     */
    private Long deviceId;

    /**
     * 项目id
     * 表字段 : broadcast_group.project_id
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table broadcast_group
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：关联麦克风id
     * 表字段：broadcast_group.device_id
     *
     * @return broadcast_group.device_id：关联麦克风id
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * 设置：关联麦克风id
     * 表字段：broadcast_group.device_id
     *
     * @param deviceId
     *            broadcast_group.device_id：关联麦克风id
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * 获取：项目id
     * 表字段：broadcast_group.project_id
     *
     * @return broadcast_group.project_id：项目id
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * 设置：项目id
     * 表字段：broadcast_group.project_id
     *
     * @param projectId
     *            broadcast_group.project_id：项目id
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }
}