package com.hoolink.sdk.bo.device;

import java.io.Serializable;
import java.util.List;

public class BroadcastGroupBO implements Serializable {
    /**
     * 广播组id
     * 表字段 : broadcast_group.id
     */
    private Long id;

    /**
     * 广播组名称 
     * 表字段 : broadcast_group.group_name
     */
    private String groupName;

    /**
     * 关联麦克风id
     * 表字段 : broadcast_group.device_id
     */
    private Long deviceId;

    /**
     * 广播组描述
     * 表字段 : broadcast_group.description
     */
    private String description;

    /**
     * 是否启用(1:启用, 0:禁用)
     * 表字段 : broadcast_group.enabled
     */
    private Boolean enabled;

    /**
     * 更新者
     * 表字段 : broadcast_group.updator
     */
    private Long updator;

    /**
     * 更新时间
     * 表字段 : broadcast_group.updated
     */
    private Long updated;

    /**
     * 创建者
     * 表字段 : broadcast_group.creator
     */
    private Long creator;

    /**
     * 创建时间
     * 表字段 : broadcast_group.created
     */
    private Long created;

    /**
     * 项目id
     * 表字段 : broadcast_group.project_id
     */
    private Long projectId;


    private List<Long> longList;


    private List<GroupBO> groupBOList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table broadcast_group
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：广播组id
     * 表字段：broadcast_group.id
     *
     * @return broadcast_group.id：广播组id
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置：广播组id
     * 表字段：broadcast_group.id
     *
     * @param id
     *            broadcast_group.id：广播组id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取：广播组名称 
     * 表字段：broadcast_group.group_name
     *
     * @return broadcast_group.group_name：广播组名称 
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * 设置：广播组名称 
     * 表字段：broadcast_group.group_name
     *
     * @param groupName
     *            broadcast_group.group_name：广播组名称 
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * 获取：关联麦克风id
     * 表字段：broadcast_group.device_id
     *
     * @return broadcast_group.device_id：关联麦克风id
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * 设置：关联麦克风id
     * 表字段：broadcast_group.device_id
     *
     * @param deviceId
     *            broadcast_group.device_id：关联麦克风id
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * 获取：广播组描述
     * 表字段：broadcast_group.description
     *
     * @return broadcast_group.description：广播组描述
     */
    public String getDescription() {
        return description;
    }

    /**
     * 设置：广播组描述
     * 表字段：broadcast_group.description
     *
     * @param description
     *            broadcast_group.description：广播组描述
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * 获取：是否启用(1:启用, 0:禁用)
     * 表字段：broadcast_group.enabled
     *
     * @return broadcast_group.enabled：是否启用(1:启用, 0:禁用)
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * 设置：是否启用(1:启用, 0:禁用)
     * 表字段：broadcast_group.enabled
     *
     * @param enabled
     *            broadcast_group.enabled：是否启用(1:启用, 0:禁用)
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * 获取：更新者
     * 表字段：broadcast_group.updator
     *
     * @return broadcast_group.updator：更新者
     */
    public Long getUpdator() {
        return updator;
    }

    /**
     * 设置：更新者
     * 表字段：broadcast_group.updator
     *
     * @param updator
     *            broadcast_group.updator：更新者
     */
    public void setUpdator(Long updator) {
        this.updator = updator;
    }

    /**
     * 获取：更新时间
     * 表字段：broadcast_group.updated
     *
     * @return broadcast_group.updated：更新时间
     */
    public Long getUpdated() {
        return updated;
    }

    /**
     * 设置：更新时间
     * 表字段：broadcast_group.updated
     *
     * @param updated
     *            broadcast_group.updated：更新时间
     */
    public void setUpdated(Long updated) {
        this.updated = updated;
    }

    /**
     * 获取：创建者
     * 表字段：broadcast_group.creator
     *
     * @return broadcast_group.creator：创建者
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * 设置：创建者
     * 表字段：broadcast_group.creator
     *
     * @param creator
     *            broadcast_group.creator：创建者
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * 获取：创建时间
     * 表字段：broadcast_group.created
     *
     * @return broadcast_group.created：创建时间
     */
    public Long getCreated() {
        return created;
    }

    /**
     * 设置：创建时间
     * 表字段：broadcast_group.created
     *
     * @param created
     *            broadcast_group.created：创建时间
     */
    public void setCreated(Long created) {
        this.created = created;
    }

    /**
     * 获取：项目id
     * 表字段：broadcast_group.project_id
     *
     * @return broadcast_group.project_id：项目id
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * 设置：项目id
     * 表字段：broadcast_group.project_id
     *
     * @param projectId
     *            broadcast_group.project_id：项目id
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }


    public List<Long> getLongList() {
        return longList;
    }

    public void setLongList(List<Long> longList) {
        this.longList = longList;
    }

    public List<GroupBO> getGroupBOList() {
        return groupBOList;
    }

    public void setGroupBOList(List<GroupBO> groupBOList) {
        this.groupBOList = groupBOList;
    }
}