package com.hoolink.sdk.bo.device;

import lombok.Data;

import java.io.Serializable;

@Data
public class CmdResHistoryBO implements Serializable {
    /**
     * <pre>
     * id
     * 表字段 : cmd_res_history.id
     * </pre>
     */
    private Long id;

    /**
     * <pre>
     * 功能码
     * 表字段 : cmd_res_history.cmd_code
     * </pre>
     */
    private String cmdCode;

    /**
     * <pre>
     * 设备厂家枚举类：参考DeviceTypeEnum
     * 表字段 : cmd_res_history.device_sub_type_id
     * </pre>
     */
    private Long deviceSubTypeId;

    /**
     * <pre>
     * 设备id
     * 表字段 : cmd_res_history.device_id
     * </pre>
     */
    private Long deviceId;

    /**
     * <pre>
     * 命令内容
     * 表字段 : cmd_res_history.cmd_content
     * </pre>
     */
    private String cmdContent;

    /**
     * <pre>
     * 接收时间
     * 表字段 : cmd_res_history.created
     * </pre>
     */
    private Long created;

    /**
     * <pre>
     * 命令结果
     * 表字段 : cmd_res_history.cmd_result
     * </pre>
     */
    private Integer cmdResult;

    /**
     * <pre>
     * 获取日志的txId
     * 表字段 : cmd_res_history.tx_id
     * </pre>
     */
    private String txId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cmd_res_history
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

}