package com.hoolink.sdk.bo.device;

import java.io.Serializable;

public class MiddleBroadcastGroupBO implements Serializable {
    /**
     * 主键id
     * 表字段 : middle_broadcast_group.id
     */
    private Long id;

    /**
     * 广播组id
     * 表字段 : middle_broadcast_group.broadcast_group_id
     */
    private Long broadcastGroupId;

    /**
     * 广播id
     * 表字段 : middle_broadcast_group.device_broadcast_id
     */
    private Long deviceBroadcastId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table middle_broadcast_group
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：主键id
     * 表字段：middle_broadcast_group.id
     *
     * @return middle_broadcast_group.id：主键id
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置：主键id
     * 表字段：middle_broadcast_group.id
     *
     * @param id
     *            middle_broadcast_group.id：主键id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取：广播组id
     * 表字段：middle_broadcast_group.broadcast_group_id
     *
     * @return middle_broadcast_group.broadcast_group_id：广播组id
     */
    public Long getBroadcastGroupId() {
        return broadcastGroupId;
    }

    /**
     * 设置：广播组id
     * 表字段：middle_broadcast_group.broadcast_group_id
     *
     * @param broadcastGroupId
     *            middle_broadcast_group.broadcast_group_id：广播组id
     */
    public void setBroadcastGroupId(Long broadcastGroupId) {
        this.broadcastGroupId = broadcastGroupId;
    }

    /**
     * 获取：广播id
     * 表字段：middle_broadcast_group.device_broadcast_id
     *
     * @return middle_broadcast_group.device_broadcast_id：广播id
     */
    public Long getDeviceBroadcastId() {
        return deviceBroadcastId;
    }

    /**
     * 设置：广播id
     * 表字段：middle_broadcast_group.device_broadcast_id
     *
     * @param deviceBroadcastId
     *            middle_broadcast_group.device_broadcast_id：广播id
     */
    public void setDeviceBroadcastId(Long deviceBroadcastId) {
        this.deviceBroadcastId = deviceBroadcastId;
    }
}